### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/driving-game#1]
# Motivation
In order to start the game, we want to be able to view the car.

# Task Implementation
- [ ] Get the files configured
- [ ] Create necessary files to start. 
- [ ] Create classes and elements to configure to show the car.

# Wireframe
![screen shot 2017-06-29 at 3 31 30 pm](https://user-images.githubusercontent.com/26865352/27713326-0c3e47d4-5ce0-11e7-97ba-c8d974a22265.png)
