### ISSUE TITLE
User can collect fuel to keep the car running

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/driving-game#11]
# Motivation
To add some fun to this, we want to create a game where the objective is to drive as long as you can without running out of fuel. 

# Task Implementation
- [x] Create a bar to show current fuel left.
- [x] Create an icon on the map to show where to pick up the fuel.
- [x] Create an indicator to show how many miles you've drive so far. 
- [x] If you run out of fuel, prompt the user that the game is over, and show them the final score.

# Wireframe
![screen shot 2017-06-30 at 3 52 46 pm](https://user-images.githubusercontent.com/26865352/27756438-3589cfb0-5dac-11e7-8dac-94e08380d3e4.png)
