### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/driving-game#3]
# Motivation
Now that the car can move, we want to be able to stop the car. 

# Task Implementation 
- [ ] Create a stop button
- [ ] Register that stop button to an event listener
- [ ] Make sure when the button is clicked the car will stop. 
- [ ] Make sure that the map reflects that. 

# Wireframe
![screen shot 2017-06-29 at 3 34 38 pm](https://user-images.githubusercontent.com/26865352/27713525-fc29b260-5ce0-11e7-875f-a97d1ef7e394.png)
